name: PHPUnit Tests

on:
  push:
    branches:
      - develop
  workflow_dispatch:
  pull_request:
  # Once weekly On Sundays at 00:00 UTC.
  schedule:
    - cron: '0 0 * * 0'

jobs:
  # Runs the PHPUnit tests for ClassicPress.
  #
  # Performs the following steps:
  # - Cancel workflow if PR updated.
  # - Checkout ClassicPress.
  # - Set environment variables.
  # - Read .nvmrc.
  # - Installs NodeJS.
  # - Sets up caching for NPM.
  # - Login at Docker Hub to increase access limits
  # - Setup, wait for and initialise MySQL.
  # - Installs NPM dependencies using install-changed to hash the `package.json` file.
  # - Configure PHP.
  # - Set up locale.
  # - Install PHPUnit and Composer dependencies.
  # - Make Composer packages available globally.
  # - Log debug information.
  # - Create config file.
  # - Set up object cache if needed for memcached tests.
  # - Set up a Memcached server if needed.
  # - Clone PHP.net if needed for unit tests.
  # - Run PHPUnit Tests.
  test-php:
    name: "PHP ${{ matrix.php }} on MySQL ${{matrix.mysql}}${{ matrix.memcached && ' with memcached' || '' }}${{ 'xdebug' == matrix.coverage && ' with XDebug' || '' }}${{ matrix.experimental && ' - Experimental' || '' }}"
    runs-on: ubuntu-24.04
    if: ${{ github.repository == 'ClassicPress/ClassicPress' || github.event_name == 'pull_request' }}
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.4', '8.3', '8.2', '8.1', '8.0', '7.4' ]
        mysql: [ '5.7', '8.0' ]
        memcached: [ false ]
        coverage: [ none ]
        experimental: [ false ]
        include:
          - php: '8.0'
            mysql: '5.7'
            memcached: true
            coverage: none
            experimental: false
          - php: '8.2'
            mysql: '5.7'
            memcached: true
            coverage: none
            experimental: false
          - php: '8.3'
            mysql: '5.7'
            memcached: true
            coverage: none
            experimental: false
          - php: '8.0'
            mysql: '8.0'
            memcached: true
            coverage: none
            experimental: false
          - php: '8.2'
            mysql: '8.0'
            memcached: true
            coverage: none
            experimental: false
          - php: '8.3'
            mysql: '8.0'
            memcached: true
            coverage: none
            experimental: false
          - php: '8.3'
            mysql: '8.0'
            memcached: false
            coverage: xdebug
            experimental: false

    steps:
      - name: Cancel previous runs of this workflow (pull requests only)
        if: ${{ github.event_name == 'pull_request' }}
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Configure environment variables
        run: |
          echo "PHP_FPM_UID=$(id -u)" >> $GITHUB_ENV
          echo "PHP_FPM_GID=$(id -g)" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read .nvmrc
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvmrc

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '${{ steps.nvmrc.outputs.NVMRC }}'

      - name: Use cached Node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Login to Docker Hub
        if: ${{ github.event_name != 'pull_request' || ( github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false ) }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql root password: "password"
          mysql version: "${{ matrix.mysql }}"

      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping --host=127.0.0.1 --port 3306 -u root -ppassword --silent; do
            sleep 1
          done

      - name: Initialise MySQL
        run: |
          mysql --host 127.0.0.1 --port 3306 -u root -ppassword -e "SELECT @@VERSION"
          mysql --host 127.0.0.1 --port 3306 -u root -ppassword < tools/local-env/mysql-init.sql
          mysql --host 127.0.0.1 --port 3306 -u root -ppassword -e "SHOW DATABASES"

      - name: Install dependencies
        run: npx install-changed --install-command="npm ci"

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          ini-values: >-
            mysql.default_host=127.0.0.1,
            mysql.default_port=3306,
            mysql.default_socket=/var/run/mysqld/mysqld.sock
          extensions: >-
            bcmath,
            curl,
            dom,
            exif,
            gd,
            iconv,
            imagick,
            intl,
            libxml,
            mbstring,
            memcached,
            mysql,
            mysqli,
            pcntl,
            pdo,
            pdo_mysql,
            pdo_sqlite,
            soap,
            sqlite,
            zip
          coverage: "${{ matrix.coverage }}"

      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y libavif-dev libwebp-dev libvpx-dev libmagic-dev libmagickcore-dev libmagickwand-dev imagemagick php${{ matrix.php }}-imagick

      - name: Set up locale
        run: |
          sudo locale-gen es_ES.UTF-8 fr_FR.UTF-8 ru_RU.UTF-8
          sudo update-locale LC_ALL="es_ES.UTF-8 fr_FR.UTF-8 ru_RU.UTF-8"

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: "--no-progress --no-ansi --no-interaction"

      - name: Make Composer packages available globally
        run: echo "${PWD}/vendor/bin" >> $GITHUB_PATH

      - name: Show debug information
        run: |
          set +e
          set -x
          npm --version
          node --version
          curl --version
          git --version
          svn --version
          php --version
          phpunit --version
          composer --version
          grunt --version
          lsb_release -a
          localectl list-locales

      - name: Create ClassicPress config file for tests
        run: |
          cp wp-tests-config-sample.php wp-tests-config.php
          sed -i 's/youremptytestdbnamehere/classicpress_develop_tests/g' wp-tests-config.php
          sed -i 's/yourusernamehere/root/g' wp-tests-config.php
          sed -i 's/yourpasswordhere/password/g' wp-tests-config.php
          sed -i 's/localhost/127.0.0.1/g' wp-tests-config.php

      - name: Set up object cache
        if: ${{ matrix.memcached }}
        run: |
          cp tests/phpunit/includes/object-cache.php src/wp-content/object-cache.php

      - name: Set up a Memcached server
        if: ${{ matrix.memcached }}
        uses: niden/actions-memcached@v7

      - name: Run PHPUnit default
        env:
          WP_DB_HOST: 127.0.0.1:3306
        run: grunt phpunit:default
        continue-on-error: ${{ matrix.experimental }}

      - name: Run PHPUnit ajax
        env:
          WP_DB_HOST: 127.0.0.1:3306
        run: grunt phpunit:ajax
        continue-on-error: ${{ matrix.experimental }}

      - name: Run PHPUnit multisite
        env:
          WP_DB_HOST: 127.0.0.1:3306
        run: grunt phpunit:multisite
        continue-on-error: ${{ matrix.experimental }}

      - name: Run PHPUnit ms-files
        env:
          WP_DB_HOST: 127.0.0.1:3306
        run: grunt phpunit:ms-files
        continue-on-error: ${{ matrix.experimental }}

      - name: Run PHPUnit external-http
        env:
          WP_DB_HOST: 127.0.0.1:3306
        run: grunt phpunit:external-http
        continue-on-error: ${{ matrix.experimental }}

      - name: Run PHPUnit restapi-jsclient
        env:
          WP_DB_HOST: 127.0.0.1:3306
        run: grunt phpunit:restapi-jsclient
        continue-on-error: ${{ matrix.experimental }}

      - name: Run PHPUnit wp-api-client-fixtures
        env:
          WP_DB_HOST: 127.0.0.1:3306
        run: grunt phpunit:wp-api-client-fixtures
        continue-on-error: ${{ matrix.experimental }}
