name: PHPUnit Tests

on:
  push:
    branches:
      - develop
  workflow_dispatch:
  pull_request:
  # Once weekly On Sundays at 00:00 UTC.
  schedule:
    - cron: '0 0 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

# Disable permissions for all available scopes by default.
# Required permissions are configured at the job level.
permissions: {}

jobs:
  #
  # Creates a PHPUnit test job for each PHP/Database combination.
  #
  test-with-mysql:
    name: "PHP ${{ matrix.php }}"
    uses: ./.github/workflows/reusable-phpunit-tests.yml
    permissions:
      contents: read
    secrets: inherit
    if: ${{ github.repository == 'ClassicPress/ClassicPress' || github.event_name == 'pull_request' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
        php: [ '7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5' ]
        db-type: [ 'mysql' ]
        db-version: [ '5.7', '8.0' ]
        multisite: [ false, true ]
        memcached: [ false ]
        coverage: [ none ]
        experimental: [ false ]
        include:
          - os: ubuntu-22.04
            php: '8.3'
            db-version: '5.7'
            db-type: mysql
            multisite: false
            memcached: true
            coverage: none
            experimental: false
          - os: ubuntu-22.04
            php: '8.4'
            db-version: '5.7'
            db-type: mysql
            multisite: false
            memcached: true
            coverage: none
            experimental: false
          - os: ubuntu-22.04
            php: '8.3'
            db-version: '8.0'
            db-type: mysql
            multisite: false
            memcached: true
            coverage: none
            experimental: false
          - os: ubuntu-22.04
            php: '8.4'
            db-version: '8.0'
            db-type: mysql
            multisite: false
            memcached: true
            coverage: none
            experimental: false
          - os: ubuntu-22.04
            php: '8.3'
            db-version: '5.7'
            db-type: mysql
            multisite: true
            memcached: true
            coverage: none
            experimental: false
          - os: ubuntu-22.04
            php: '8.4'
            db-version: '5.7'
            db-type: mysql
            multisite: true
            memcached: true
            coverage: none
            experimental: false
          - os: ubuntu-22.04
            php: '8.3'
            db-version: '8.0'
            db-type: mysql
            multisite: true
            memcached: true
            coverage: none
            experimental: false
          - os: ubuntu-22.04
            php: '8.4'
            db-version: '8.0'
            db-type: mysql
            multisite: true
            memcached: true
            coverage: none
            experimental: false
          - os: ubuntu-22.04
            php: '8.4'
            db-version: '8.0'
            db-type: mysql
            multisite: false
            memcached: false
            coverage: xdebug
            experimental: false
          - os: ubuntu-22.04
            php: '8.4'
            db-version: '8.0'
            db-type: mysql
            multisite: true
            memcached: false
            coverage: xdebug
            experimental: false
    with:
      os: ${{ matrix.os }}
      php: ${{ matrix.php }}
      db-type: ${{ matrix.db-type }}
      db-version: ${{ matrix.db-version }}
      multisite: ${{ matrix.multisite }}
      memcached: ${{ matrix.memcached }}
      coverage: ${{ matrix.coverage }}
      experimental: ${{ matrix.experimental }}

  test-with-mariadb:
    name: "PHP ${{ matrix.php }}${{ matrix.memcached && ' with memcached' || '' }}"
    uses: ./.github/workflows/reusable-phpunit-tests.yml
    permissions:
      contents: read
    secrets: inherit
    if: ${{ github.repository == 'ClassicPress/ClassicPress' || github.event_name == 'pull_request' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
        php: [ '7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5' ]
        db-type: [ 'mariadb' ]
        db-version: [ '10.4', '11.4' ]
        multisite: [ false, true ]
        memcached: [ false ]
        coverage: [ none ]
        experimental: [ false ]
    with:
      os: ${{ matrix.os }}
      php: ${{ matrix.php }}
      db-type: ${{ matrix.db-type }}
      db-version: ${{ matrix.db-version }}
      multisite: ${{ matrix.multisite }}
      memcached: ${{ matrix.memcached }}
      coverage: ${{ matrix.coverage }}
      experimental: ${{ matrix.experimental }}
