name: Add Triage Label

on:
  issues:
    types: opened

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions-ecosystem/action-add-labels@v1
        if: github.event.issue.labels[0] == null
        with:
          labels: 'status: needs triage'
