name: Welcome New Contributors

on:
  pull_request_target:
    types:
      opened
  issues:
    types:
      opened

# Disable permissions for all available scopes by default.
# Required permissions are configured at the job level.
permissions: {}

jobs:
  # Comments on a pull request when the author is a new contributor.
  post-welcome-message:
    name: Welcome message
    permissions:
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          issue_message: |
            Hi @{{ github.actor }}! 👋

            Thank you for opening an issue at ClassicPress! 💖

            It looks like this is your first issue. We appreciate and value your time!

            If you haven't already, please give us as much information about the issue. If you can include steps on how to re-create the issue, that would be really helpful.

            Thank you,
            ClassicPress Core Team.
          pr_message: |
            Hi @{{ github.actor }}! 👋

            Thank you for your contribution to ClassicPress! 💖

            It looks like this is your first pull request. We appreciate and value your contribution!

            Please read our [contribution guide](https://github.com/ClassicPress/ClassicPress/blob/develop/.github/CONTRIBUTING.md) to find out how you can be more involved.

            Thank you,
            ClassicPress Core Team.
